using Assetra.Application.Sync;
using Assetra.Core.Interfaces;
using Assetra.Core.Models;
using Assetra.WPF.Infrastructure;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Assetra.WPF.Features.Settings;

/// <summary>
/// Sync 設定 + 手動觸發 ViewModel。三類欄位：
/// <list type="bullet">
///   <item><b>持久化</b>（綁 <see cref="AppSettings"/>）：<c>Enabled</c> / <c>BackendUrl</c> / <c>AuthToken</c>。
///     `DeviceId` 與 <c>SaltBase64</c> 由 <see cref="SyncCoordinator"/> 在首次同步時自動產生並寫入 settings。</item>
///   <item><b>僅在記憶體</b>（不寫 settings）：<see cref="Passphrase"/> —— 只用來 KDF → AES key，用完即丟。</item>
///   <item><b>狀態</b>（讀回顯）：<c>LastSyncAt</c> / <c>LastPulled</c> / <c>LastPushed</c> /
///     <c>AutoResolved</c> / <c>ManualConflicts</c> / <c>StatusMessage</c>。</item>
/// </list>
/// </summary>
public partial class SyncSettingsViewModel : ObservableObject
{
    private readonly IAppSettingsService _settings;
    private readonly SyncCoordinator _coordinator;
    private readonly SyncPassphraseCache _passphraseCache;
    private readonly ILocalizationService _loc;

    [ObservableProperty]
    private bool _enabled;

    [ObservableProperty]
    private string _backendUrl = string.Empty;

    [ObservableProperty]
    private string _authToken = string.Empty;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SyncNowCommand))]
    private string _passphrase = string.Empty;

    [ObservableProperty]
    private string _deviceId = string.Empty;

    [ObservableProperty]
    private string _statusMessage = string.Empty;

    [ObservableProperty]
    private DateTimeOffset? _lastSyncAt;

    [ObservableProperty]
    private int _lastPulled;

    [ObservableProperty]
    private int _lastPushed;

    [ObservableProperty]
    private int _autoResolved;

    [ObservableProperty]
    private int _manualConflicts;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(SyncNowCommand))]
    private bool _isSyncing;

    [ObservableProperty]
    private int _intervalMinutes;

    [ObservableProperty]
    private bool _cachePassphraseForBackground;

    public event Action? PassphraseCleared;

    public SyncSettingsViewModel(
        IAppSettingsService settings,
        SyncCoordinator coordinator,
        SyncPassphraseCache passphraseCache,
        ILocalizationService? localization = null)
    {
        ArgumentNullException.ThrowIfNull(settings);
        ArgumentNullException.ThrowIfNull(coordinator);
        ArgumentNullException.ThrowIfNull(passphraseCache);
        _settings = settings;
        _coordinator = coordinator;
        _passphraseCache = passphraseCache;
        _loc = localization ?? NullLocalizationService.Instance;
        Reload();
    }

    public void Reload()
    {
        var s = _settings.Current;
        Enabled = s.SyncEnabled;
        BackendUrl = s.SyncBackendUrl;
        AuthToken = s.SyncAuthToken;
        DeviceId = s.SyncDeviceId;
        IntervalMinutes = s.SyncIntervalMinutes;
    }

    [RelayCommand]
    private async Task SaveSettingsAsync()
    {
        var s = _settings.Current with
        {
            SyncEnabled = Enabled,
            SyncBackendUrl = BackendUrl?.Trim() ?? string.Empty,
            SyncAuthToken = AuthToken?.Trim() ?? string.Empty,
            SyncIntervalMinutes = Math.Max(0, IntervalMinutes),
        };
        await _settings.SaveAsync(s).ConfigureAwait(true);
        if (!CachePassphraseForBackground)
            _passphraseCache.Clear();
        StatusMessage = Text("Settings.Sync.Status.Saved", "Saved.");
    }

    partial void OnCachePassphraseForBackgroundChanged(bool value)
    {
        if (!value)
            _passphraseCache.Clear();
    }

    private bool CanSyncNow() => !IsSyncing && !string.IsNullOrEmpty(Passphrase);

    [RelayCommand(CanExecute = nameof(CanSyncNow))]
    private async Task SyncNowAsync()
    {
        IsSyncing = true;
        try
        {
            // Save first so coordinator reads fresh settings
            await SaveSettingsAsync();
            StatusMessage = Text("Settings.Sync.Status.Syncing", "Syncing...");

            var result = await _coordinator.SyncAsync(Passphrase).ConfigureAwait(true);
            LastSyncAt = result.CompletedAt;
            LastPulled = result.PulledCount;
            LastPushed = result.PushedCount;
            AutoResolved = result.AutoResolvedConflicts;
            ManualConflicts = result.ManualConflicts;
            StatusMessage = ManualConflicts > 0
                ? Text("Settings.Sync.Status.DoneWithConflicts", "Done. {0} conflict(s) need manual review.", ManualConflicts)
                : Text("Settings.Sync.Status.Done", "Done.");

            // Reload device id (may have just been generated by the coordinator)
            DeviceId = _settings.Current.SyncDeviceId;

            // 使用者明確勾選才把密語放進記憶體快取，讓 BackgroundSyncService 自動觸發
            if (CachePassphraseForBackground)
                _passphraseCache.Set(Passphrase);
            else
                _passphraseCache.Clear();
        }
        catch (Exception ex)
        {
            StatusMessage = Text("Settings.Sync.Status.Failed", "Failed: {0}", ex.Message);
        }
        finally
        {
            IsSyncing = false;
            // Wipe passphrase from VM — cache (if user opted in) holds the only remaining copy
            Passphrase = string.Empty;
            PassphraseCleared?.Invoke();
        }
    }

    private string Text(string key, string fallback, params object[] args)
    {
        var template = _loc.Get(key, fallback);
        return args.Length == 0 ? template : string.Format(template, args);
    }
}
